### ISSUE TITLE
Подсветка bsl блоков 

### ISSUE THREAD

**Issue by nixel2007** [autumn-library/docs#7]
* Убрать highlight.js
* Научить родную расцветку красить бсл
* поменять код языка в блоках на bsl

**Comment by Bayselonarrend** [comment]
VitePress использует [shiki](https://github.com/shikijs/shiki). Там нет bsl в [поддерживаемых языках](https://shiki.style/languages)

**Comment by sfaqer** [comment]
Можно свой подгрузить всё таки: https://shiki.style/guide/load-lang

**Comment by Bayselonarrend** [comment]
А есть описание bsl на текстмейте?

**Comment by Bayselonarrend** [comment]
А, ну да, в 1c-syntax есть, тогда да
